"""Scraped Build123D documentation — data package.

The contents of this directory are generated by
``scripts/scrape_build123d_docs.py``. Do not hand-edit the ``pages/`` files;
edit the curated overlay in ``external_libs_overlay.md`` and re-run the
scraper.

REQ: FLH-F-029, FLH-D-026
"""
